// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/HooYa-Bigdata/policyservice/config"
	"github.com/HooYa-Bigdata/policyservice/genproto/v1"
	"github.com/HooYa-Bigdata/policyservice/service"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf *config.Config) (v1.PolicyServiceServer, error) {
	policyServiceClient, err := service.NewClient(conf)
	if err != nil {
		return nil, err
	}
	policyServiceServer, err := service.NewServer(conf, policyServiceClient)
	if err != nil {
		return nil, err
	}
	return policyServiceServer, nil
}
